version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "develop"
    ignore:
      - dependency-name: "org.spockframework:spock-bom"
        versions: ["2.3-groovy-4.0"]

  - package-ecosystem: "github-actions"
    directory: "/" # Location of the GitHub Actions workflows
    schedule:
      interval: "weekly"